import { Tool, Loan, Toolbox } from './types';

export const MOCK_TOOLS: Tool[] = [
  {
    id: '1',
    name: 'Cordless Drill DCD791',
    category: 'Power Tools',
    brand: 'DeWalt',
    serialNumber: 'DW-791-001',
    status: 'available',
    location: 'Shelf A1',
    purchaseDate: '2023-01-15',
    lastMaintenance: '2024-01-10',
    nextMaintenance: '2025-01-10',
    imageUrl: 'https://picsum.photos/seed/drill/200/200',
  },
  {
    id: '2',
    name: 'Circular Saw 5007MG',
    category: 'Power Tools',
    brand: 'Makita',
    serialNumber: 'MK-5007-042',
    status: 'borrowed',
    location: 'Shelf A2',
    purchaseDate: '2023-03-20',
    lastMaintenance: '2024-02-15',
    nextMaintenance: '2025-02-15',
    imageUrl: 'https://picsum.photos/seed/saw/200/200',
  },
  {
    id: '3',
    name: 'Laser Level 360',
    category: 'Measuring Tools',
    brand: 'Bosch',
    serialNumber: 'BS-360-112',
    status: 'maintenance',
    location: 'Repair Shop',
    purchaseDate: '2023-06-10',
    lastMaintenance: '2024-03-01',
    nextMaintenance: '2024-04-01',
    imageUrl: 'https://picsum.photos/seed/laser/200/200',
  },
  {
    id: '4',
    name: 'Heavy Duty Jackhammer',
    category: 'Construction',
    brand: 'Hilti',
    serialNumber: 'HT-JH-99',
    status: 'available',
    location: 'Bay 4',
    purchaseDate: '2022-11-05',
    lastMaintenance: '2023-11-05',
    nextMaintenance: '2024-05-05',
    imageUrl: 'https://picsum.photos/seed/jackhammer/200/200',
  },
  {
    id: '5',
    name: 'Digital Multimeter',
    category: 'Electrical',
    brand: 'Fluke',
    serialNumber: 'FL-87-V',
    status: 'available',
    location: 'Cabinet B',
    purchaseDate: '2023-08-12',
    lastMaintenance: '2024-02-20',
    nextMaintenance: '2025-02-20',
    imageUrl: 'https://picsum.photos/seed/multimeter/200/200',
  }
];

export const MOCK_LOANS: Loan[] = [
  {
    id: 'L1',
    toolId: '2',
    toolName: 'Circular Saw 5007MG',
    typeSize: '5007MG',
    borrowerName: 'Andi Wijaya',
    section: 'Track',
    shift: 'Day',
    borrowDate: '2024-03-25T08:00:00Z',
    status: 'active',
  },
  {
    id: 'L2',
    toolId: '1',
    toolName: 'Cordless Drill DCD791',
    typeSize: 'DCD791',
    borrowerName: 'Budi Santoso',
    section: 'Wheel Big',
    shift: 'Night',
    borrowDate: '2024-03-10T20:00:00Z',
    status: 'returned',
  }
];

export const INITIAL_INVENTORY = [
  { id: 'INV003', toolId: 'TR-003', category: 'Special Tool', merk: '', toolDesc: 'AC Kit Crimper Hydraulic', typeSize: 'FJC 2806', qty: 1 },
  { id: 'INV004', toolId: 'TR-004', category: 'Special Tool', merk: '', toolDesc: 'AC Kit Crimper Hydraulic', typeSize: 'FJC 2806', qty: 1 },
  { id: 'INV005', toolId: 'TR-005', category: 'Common Tool', merk: '', toolDesc: 'Air Impact Wrench', typeSize: '1" Big Long', qty: 1 },
  { id: 'INV006', toolId: 'TR-006', category: 'Common Tool', merk: '', toolDesc: 'Air Impact Wrench', typeSize: '1" Big Short', qty: 1 },
  { id: 'INV007', toolId: 'TR-007', category: 'Common Tool', merk: '', toolDesc: 'Air Impact Wrench', typeSize: '1" Short', qty: 1 },
  { id: 'INV008', toolId: 'TR-008', category: 'Common Tool', merk: '', toolDesc: 'Air Impact Wrench', typeSize: '3/4"', qty: 1 },
  { id: 'INV009', toolId: 'TR-009', category: 'Common Tool', merk: '', toolDesc: 'Air Impact Wrench', typeSize: '3/4"', qty: 1 },
  { id: 'INV010', toolId: 'TR-010', category: 'Common Tool', merk: 'Makita', toolDesc: 'Angle Grinder', typeSize: 'GA4030', qty: 1 },
  { id: 'INV011', toolId: 'TR-011', category: 'Common Tool', merk: 'Fluke', toolDesc: 'Avo Meter', typeSize: '17B+', qty: 1 },
  { id: 'INV012', toolId: 'TR-012', category: 'Common Tool', merk: 'Sanwa', toolDesc: 'Avo Meter', typeSize: 'CD800a', qty: 1 },
  { id: 'INV013', toolId: 'TR-013', category: 'Common Tool', merk: 'Sanwa', toolDesc: 'Avo Meter', typeSize: 'CD800a', qty: 1 },
  { id: 'INV014', toolId: 'TR-014', category: 'Common Tool', merk: 'Sanwa', toolDesc: 'Avo Meter', typeSize: 'CD800a', qty: 1 },
  { id: 'INV015', toolId: 'TR-015', category: 'Common Tool', merk: 'Sanwa', toolDesc: 'Avo Meter', typeSize: 'CD800a', qty: 1 },
  { id: 'INV016', toolId: 'TR-016', category: 'Common Tool', merk: '', toolDesc: 'Cable Roll', typeSize: '50 Meter', qty: 1 },
  { id: 'INV017', toolId: 'TR-017', category: 'Common Tool', merk: '', toolDesc: 'Cable Roll', typeSize: '50 Meter', qty: 1 },
  { id: 'INV018', toolId: 'TR-018', category: 'Common Tool', merk: '', toolDesc: 'Cable Roll', typeSize: '25 Meter', qty: 1 },
  { id: 'INV019', toolId: 'TR-019', category: 'Common Tool', merk: '', toolDesc: 'Cable Roll', typeSize: '25 Meter', qty: 1 },
  { id: 'INV020', toolId: 'TR-020', category: 'Common Tool', merk: '', toolDesc: 'Chicken Bar', typeSize: '22 Milimeter', qty: 1 },
  { id: 'INV021', toolId: 'TR-021', category: 'Common Tool', merk: '', toolDesc: 'Compound Gas Monitor', typeSize: 'WT8811', qty: 1 },
  { id: 'INV022', toolId: 'TR-022', category: 'Common Tool', merk: '', toolDesc: 'Cooper Hammer', typeSize: '10 Kg', qty: 3 },
  { id: 'INV023', toolId: 'TR-023', category: 'Common Tool', merk: '', toolDesc: 'Cooper Hammer', typeSize: '5 Kg', qty: 3 },
  { id: 'INV024', toolId: 'TR-024', category: 'Common Tool', merk: '', toolDesc: 'Cooper Hammer', typeSize: '3 Kg', qty: 1 },
  { id: 'INV025', toolId: 'TR-025', category: 'Common Tool', merk: 'INGCO', toolDesc: 'Cordless Solder Iron', typeSize: '', qty: 1 },
  { id: 'INV026', toolId: 'TR-026', category: 'Common Tool', merk: '', toolDesc: 'Cylinder Pressure Meter', typeSize: '0-1000 Psi', qty: 1 },
  { id: 'INV027', toolId: 'TR-027', category: 'Common Tool', merk: '', toolDesc: 'Dial Bore Gauge', typeSize: 'EXD-315 SERIES', qty: 1 },
  { id: 'INV028', toolId: 'TR-028', category: 'Common Tool', merk: 'Rivati', toolDesc: 'Dial Gauge', typeSize: '', qty: 1 },
  { id: 'INV029', toolId: 'TR-029', category: 'Common Tool', merk: '', toolDesc: 'Dial Gauge', typeSize: 'Unknown', qty: 1 },
  { id: 'INV030', toolId: 'TR-030', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Die Grinder', typeSize: '', qty: 1 },
  { id: 'INV031', toolId: 'TR-031', category: 'Common Tool', merk: 'Makita', toolDesc: 'Die Grinder', typeSize: 'M9100B', qty: 1 },
  { id: 'INV032', toolId: 'TR-032', category: 'Common Tool', merk: '', toolDesc: 'Digital Tachometer', typeSize: 'DT-6236B', qty: 1 },
  { id: 'INV033', toolId: 'TR-033', category: 'Common Tool', merk: '', toolDesc: 'Ear Muff', typeSize: '3"', qty: 1 },
  { id: 'INV034', toolId: 'TR-034', category: 'Common Tool', merk: '', toolDesc: 'Engine Pressure-Loss Tester', typeSize: 'DRV 05-041113_5', qty: 1 },
  { id: 'INV035', toolId: 'TR-035', category: 'Common Tool', merk: '', toolDesc: 'Engraver', typeSize: '15W E15', qty: 1 },
  { id: 'INV036', toolId: 'TR-036', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Heat Gun', typeSize: 'KW0700859', qty: 1 },
  { id: 'INV037', toolId: 'TR-037', category: 'Common Tool', merk: 'Makita', toolDesc: 'Heat Gun', typeSize: 'HG6530V', qty: 1 },
  { id: 'INV038', toolId: 'TR-038', category: 'Common Tool', merk: 'Wipro', toolDesc: 'Hydraulic Jack', typeSize: '30T', qty: 5 },
  { id: 'INV039', toolId: 'TR-039', category: 'Common Tool', merk: 'Wipro', toolDesc: 'Hydraulic Jack', typeSize: '20T', qty: 5 },
  { id: 'INV040', toolId: 'TR-040', category: 'Common Tool', merk: 'Wipro', toolDesc: 'Hydraulic Jack', typeSize: '10T', qty: 2 },
  { id: 'INV041', toolId: 'TR-041', category: 'Common Tool', merk: 'Wipro', toolDesc: 'Hydraulic Jack', typeSize: '5T', qty: 2 },
  { id: 'INV042', toolId: 'TR-042', category: 'Common Tool', merk: '', toolDesc: 'Hydraulic Torque Wrench', typeSize: 'TSP300 Pro Series Swivel', qty: 1 },
  { id: 'INV043', toolId: 'TR-043', category: 'Common Tool', merk: 'Enerpac', toolDesc: 'Hydraulic Torque Wrench Pump', typeSize: 'Z-Class', qty: 1 },
  { id: 'INV044', toolId: 'TR-044', category: 'Common Tool', merk: 'Enerpac', toolDesc: 'Hydraulic Torque Wrench Pump', typeSize: 'ZU4-Series', qty: 1 },
  { id: 'INV045', toolId: 'TR-045', category: 'Common Tool', merk: 'Makita', toolDesc: 'Impact Wrench Cordless', typeSize: 'DTW1001RTJ', qty: 1 },
  { id: 'INV046', toolId: 'TR-046', category: 'Common Tool', merk: 'Makita', toolDesc: 'Impact Drill', typeSize: 'HP1630', qty: 1 },
  { id: 'INV047', toolId: 'TR-047', category: 'Common Tool', merk: '', toolDesc: 'Mini Grinder', typeSize: 'MLR-MG005F', qty: 1 },
  { id: 'INV048', toolId: 'TR-048', category: 'Common Tool', merk: '', toolDesc: 'Pen Type Meter', typeSize: 'A3002', qty: 1 },
  { id: 'INV049', toolId: 'TR-049', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Push Pull Gauge', typeSize: 'KW0600198', qty: 1 },
  { id: 'INV050', toolId: 'TR-050', category: 'Common Tool', merk: 'Tekiro', toolDesc: 'Ring Piston Compressor', typeSize: '', qty: 1 },
  { id: 'INV051', toolId: 'TR-051', category: 'Common Tool', merk: '', toolDesc: 'Spray Gun', typeSize: 'F75G-2', qty: 3 },
  { id: 'INV052', toolId: 'TR-052', category: 'Common Tool', merk: 'Fluke', toolDesc: 'Thermometer Gun', typeSize: '', qty: 1 },
  { id: 'INV053', toolId: 'TR-053', category: 'Common Tool', merk: 'Fluke', toolDesc: 'Thermometer Gun', typeSize: '', qty: 1 },
  { id: 'INV054', toolId: 'TR-054', category: 'Common Tool', merk: '', toolDesc: 'Titanium Step Drill Set', typeSize: '4-12 mm, 4-32 mm & 4-20 mm', qty: 1 },
  { id: 'INV055', toolId: 'TR-055', category: 'Common Tool', merk: '', toolDesc: 'Torque Multiplier', typeSize: 'J6232CERT', qty: 1 },
  { id: 'INV056', toolId: 'TR-056', category: 'Common Tool', merk: '', toolDesc: 'Torque Multiplier', typeSize: 'J6232CERT', qty: 1 },
  { id: 'INV057', toolId: 'TR-057', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '50 - 200 Kg', qty: 1 },
  { id: 'INV058', toolId: 'TR-058', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '49 - 105 Kg', qty: 1 },
  { id: 'INV059', toolId: 'TR-059', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '20 - 100 Kg', qty: 2 },
  { id: 'INV060', toolId: 'TR-060', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '22 - 82 Kg', qty: 1 },
  { id: 'INV061', toolId: 'TR-061', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '7 - 35 Kg', qty: 2 },
  { id: 'INV062', toolId: 'TR-062', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '5 - 23 Kg', qty: 1 },
  { id: 'INV063', toolId: 'TR-063', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '3 - 14 Kg', qty: 3 },
  { id: 'INV064', toolId: 'TR-064', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '1,2 - 7 Kg', qty: 2 },
  { id: 'INV065', toolId: 'TR-065', category: 'Common Tool', merk: '', toolDesc: 'Torque Wrench', typeSize: '0,5 - 3,4 Kg', qty: 1 },
  { id: 'INV066', toolId: 'TR-066', category: 'Common Tool', merk: '', toolDesc: 'Tracker Bearing', typeSize: '3"', qty: 3 },
  { id: 'INV067', toolId: 'TR-067', category: 'Common Tool', merk: '', toolDesc: 'Tracker Bearing', typeSize: '8"', qty: 1 },
  { id: 'INV068', toolId: 'TR-068', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Tracker Bearing Separator Set', typeSize: 'KW0102602 4 Inch', qty: 1 },
  { id: 'INV069', toolId: 'TR-069', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Tracker Bearing Separator Set', typeSize: 'KW0102602 4 Inch', qty: 1 },
  { id: 'INV070', toolId: 'TR-070', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Transmission Jack 0.5 Ton', typeSize: 'KW0500759', qty: 1 },
  { id: 'INV071', toolId: 'TR-071', category: 'Common Tool', merk: '', toolDesc: 'Vacum Pump AC', typeSize: 'VE280', qty: 1 },
  { id: 'INV072', toolId: 'TR-072', category: 'Common Tool', merk: '', toolDesc: 'Vacum Pump AC', typeSize: 'VE115N', qty: 1 },
  { id: 'INV073', toolId: 'TR-073', category: 'Common Tool', merk: '', toolDesc: 'Vacum Pump AC', typeSize: 'RS-1.5A', qty: 1 },
  { id: 'INV074', toolId: 'TR-074', category: 'Common Tool', merk: '', toolDesc: 'Vernier Caliper', typeSize: '0 - 30 Cm', qty: 1 },
  { id: 'INV075', toolId: 'TR-075', category: 'Common Tool', merk: '', toolDesc: 'Vernier Caliper', typeSize: '0 - 300 mm', qty: 1 },
  { id: 'INV076', toolId: 'TR-076', category: 'Common Tool', merk: '', toolDesc: 'Vernier Caliper', typeSize: '0 - 60 Cm', qty: 1 },
  { id: 'INV077', toolId: 'TR-077', category: 'Common Tool', merk: '', toolDesc: 'Vernier Caliper Digital', typeSize: '0 - 150 mm', qty: 1 },
  { id: 'INV078', toolId: 'TR-078', category: 'Common Tool', merk: '', toolDesc: 'Vibration Meter', typeSize: '805/805 FC', qty: 1 },
  { id: 'INV079', toolId: 'TR-079', category: 'Common Tool', merk: '', toolDesc: 'Webbing Belt', typeSize: '3 Ton', qty: 2 },
  { id: 'INV080', toolId: 'TR-080', category: 'Common Tool', merk: '', toolDesc: 'Webbing Belt', typeSize: '5 Ton', qty: 4 },
  { id: 'INV081', toolId: 'TR-081', category: 'Common Tool', merk: '', toolDesc: 'Adaptor Socket', typeSize: '1-1/2" x 1"', qty: 1 },
  { id: 'INV082', toolId: 'TR-082', category: 'Common Tool', merk: '', toolDesc: 'Adaptor Socket', typeSize: '1" x 3/4"', qty: 5 },
  { id: 'INV083', toolId: 'TR-083', category: 'Common Tool', merk: '', toolDesc: 'Adaptor Socket', typeSize: '1/2" x 3/4"', qty: 1 },
  { id: 'INV084', toolId: 'TR-084', category: 'Common Tool', merk: '', toolDesc: 'Adaptor Socket', typeSize: '3/4 x 1"', qty: 3 },
  { id: 'INV085', toolId: 'TR-085', category: 'Common Tool', merk: '', toolDesc: 'Adaptor Socket', typeSize: '3/4 x 1/2"', qty: 6 },
  { id: 'INV086', toolId: 'TR-086', category: 'Common Tool', merk: '', toolDesc: 'Adjustable Plier Wrench', typeSize: '1 Inch', qty: 1 },
  { id: 'INV087', toolId: 'TR-087', category: 'Common Tool', merk: '', toolDesc: 'Adjustable Wrench', typeSize: '18 Inch', qty: 4 },
  { id: 'INV088', toolId: 'TR-088', category: 'Common Tool', merk: '', toolDesc: 'Adjustable Wrench', typeSize: '24 Inch', qty: 2 },
  { id: 'INV089', toolId: 'TR-089', category: 'Common Tool', merk: '', toolDesc: 'Tubing Wrench', typeSize: '36 Inch', qty: 1 },
  { id: 'INV090', toolId: 'TR-090', category: 'Common Tool', merk: '', toolDesc: 'Tubing Wrench', typeSize: '24 Inch', qty: 1 },
  { id: 'INV091', toolId: 'TR-091', category: 'Common Tool', merk: '', toolDesc: 'Tubing Wrench', typeSize: '18 Inch', qty: 1 },
  { id: 'INV092', toolId: 'TR-092', category: 'Common Tool', merk: '', toolDesc: 'Tubing Wrench', typeSize: '14 Inch', qty: 1 },
  { id: 'INV093', toolId: 'TR-093', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '55mm', qty: 1 },
  { id: 'INV094', toolId: 'TR-094', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '50mm', qty: 2 },
  { id: 'INV095', toolId: 'TR-095', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '46mm', qty: 2 },
  { id: 'INV096', toolId: 'TR-096', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '41mm', qty: 2 },
  { id: 'INV097', toolId: 'TR-097', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '36mm', qty: 1 },
  { id: 'INV098', toolId: 'TR-098', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '32mm', qty: 2 },
  { id: 'INV099', toolId: 'TR-099', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '30mm', qty: 1 },
  { id: 'INV100', toolId: 'TR-100', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '23mm', qty: 1 },
  { id: 'INV101', toolId: 'TR-101', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '21mm', qty: 1 },
  { id: 'INV102', toolId: 'TR-102', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '1 - 1/8', qty: 2 },
  { id: 'INV103', toolId: 'TR-103', category: 'Common Tool', merk: '', toolDesc: 'Combination Wrench', typeSize: '1 - 1/16', qty: 2 },
  { id: 'INV104', toolId: 'TR-104', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1" x 36 mm', qty: 3 },
  { id: 'INV105', toolId: 'TR-105', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1" x 28 mm', qty: 1 },
  { id: 'INV106', toolId: 'TR-106', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1" x 27 mm', qty: 2 },
  { id: 'INV107', toolId: 'TR-107', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1" x 24 mm', qty: 3 },
  { id: 'INV108', toolId: 'TR-108', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1" x 22 mm', qty: 1 },
  { id: 'INV109', toolId: 'TR-109', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1" x 21 mm', qty: 1 },
  { id: 'INV110', toolId: 'TR-110', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 32 mm', qty: 1 },
  { id: 'INV111', toolId: 'TR-111', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 30 mm', qty: 1 },
  { id: 'INV112', toolId: 'TR-112', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 27 mm', qty: 2 },
  { id: 'INV113', toolId: 'TR-113', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 26 mm', qty: 1 },
  { id: 'INV114', toolId: 'TR-114', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 24 mm', qty: 2 },
  { id: 'INV115', toolId: 'TR-115', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 22 mm', qty: 1 },
  { id: 'INV116', toolId: 'TR-116', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '3/4" x 21 mm', qty: 1 },
  { id: 'INV117', toolId: 'TR-117', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1"x21mm (4 PT)', qty: 7 },
  { id: 'INV118', toolId: 'TR-118', category: 'Common Tool', merk: '', toolDesc: 'Deep Socket Wrench', typeSize: '1"x19mm (4 PT)', qty: 4 },
  { id: 'INV119', toolId: 'TR-119', category: 'Common Tool', merk: '', toolDesc: 'Double Ring Wrench', typeSize: '25 - 28 mm', qty: 1 },
  { id: 'INV120', toolId: 'TR-120', category: 'Common Tool', merk: '', toolDesc: 'Double Ring Wrench', typeSize: '24 - 30 mm', qty: 1 },
  { id: 'INV121', toolId: 'TR-121', category: 'Common Tool', merk: '', toolDesc: 'Double Ring Wrench', typeSize: '32 - 36 mm', qty: 1 },
  { id: 'INV122', toolId: 'TR-122', category: 'Common Tool', merk: '', toolDesc: 'Double Ring Wrench', typeSize: '20 - 22 mm', qty: 1 },
  { id: 'INV123', toolId: 'TR-123', category: 'Common Tool', merk: '', toolDesc: 'Double Ring Wrench', typeSize: '36 - 41 mm', qty: 1 },
  { id: 'INV124', toolId: 'TR-124', category: 'Common Tool', merk: '', toolDesc: 'Double Ring Wrench', typeSize: '41 - 46 mm', qty: 1 },
  { id: 'INV125', toolId: 'TR-125', category: 'Common Tool', merk: '', toolDesc: 'ELENKEY', typeSize: '19mm', qty: 4 },
  { id: 'INV126', toolId: 'TR-126', category: 'Common Tool', merk: '', toolDesc: 'ELENKEY', typeSize: '17mm', qty: 4 },
  { id: 'INV127', toolId: 'TR-127', category: 'Common Tool', merk: '', toolDesc: 'ELENKEY', typeSize: '14mm', qty: 4 },
  { id: 'INV128', toolId: 'TR-128', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '46-50mm', qty: 1 },
  { id: 'INV129', toolId: 'TR-129', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '41-46mm', qty: 5 },
  { id: 'INV130', toolId: 'TR-130', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '36-41mm', qty: 3 },
  { id: 'INV131', toolId: 'TR-131', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '32-36mm', qty: 1 },
  { id: 'INV132', toolId: 'TR-132', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '30-32mm', qty: 7 },
  { id: 'INV133', toolId: 'TR-133', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '22-26mm', qty: 1 },
  { id: 'INV134', toolId: 'TR-134', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '22-24mm', qty: 1 },
  { id: 'INV135', toolId: 'TR-135', category: 'Common Tool', merk: '', toolDesc: 'Double Open End Wrench', typeSize: '12-14mm', qty: 1 },
  { id: 'INV136', toolId: 'TR-136', category: 'Common Tool', merk: '', toolDesc: 'Extention Bar', typeSize: '1"x16"', qty: 2 },
  { id: 'INV137', toolId: 'TR-137', category: 'Common Tool', merk: '', toolDesc: 'Extention Bar', typeSize: '1"x4"', qty: 2 },
  { id: 'INV138', toolId: 'TR-138', category: 'Common Tool', merk: '', toolDesc: 'Extention Bar', typeSize: '3/4"x16"', qty: 1 },
  { id: 'INV139', toolId: 'TR-139', category: 'Common Tool', merk: '', toolDesc: 'Extention Bar', typeSize: '3/4"x8"', qty: 1 },
  { id: 'INV140', toolId: 'TR-140', category: 'Common Tool', merk: '', toolDesc: 'Sackle', typeSize: '2T', qty: 4 },
  { id: 'INV141', toolId: 'TR-141', category: 'Common Tool', merk: '', toolDesc: 'Sackle', typeSize: '1T', qty: 4 },
  { id: 'INV142', toolId: 'TR-142', category: 'Common Tool', merk: '', toolDesc: 'Single Open Wrench', typeSize: '75mm', qty: 2 },
  { id: 'INV143', toolId: 'TR-143', category: 'Common Tool', merk: '', toolDesc: 'Single Open Wrench', typeSize: '46mm', qty: 4 },
  { id: 'INV144', toolId: 'TR-144', category: 'Common Tool', merk: '', toolDesc: 'Sliding T Bar', typeSize: '1"', qty: 3 },
  { id: 'INV145', toolId: 'TR-145', category: 'Common Tool', merk: '', toolDesc: 'Sliding T Bar', typeSize: '3/4"', qty: 2 },
  { id: 'INV146', toolId: 'TR-146', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '30 mm', qty: 1 },
  { id: 'INV147', toolId: 'TR-147', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '32 mm', qty: 1 },
  { id: 'INV148', toolId: 'TR-148', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '36 mm', qty: 2 },
  { id: 'INV149', toolId: 'TR-149', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '38 mm', qty: 1 },
  { id: 'INV150', toolId: 'TR-150', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '41 mm', qty: 2 },
  { id: 'INV151', toolId: 'TR-151', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '46 mm', qty: 1 },
  { id: 'INV152', toolId: 'TR-152', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '50 mm', qty: 1 },
  { id: 'INV153', toolId: 'TR-153', category: 'Common Tool', merk: '', toolDesc: 'Sloging Wrench', typeSize: '55 mm', qty: 1 },
  { id: 'INV154', toolId: 'TR-154', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 80 mm', qty: 1 },
  { id: 'INV155', toolId: 'TR-155', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 75 mm', qty: 1 },
  { id: 'INV156', toolId: 'TR-156', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 70 mm', qty: 1 },
  { id: 'INV157', toolId: 'TR-157', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 57 mm', qty: 1 },
  { id: 'INV158', toolId: 'TR-158', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 52 mm', qty: 1 },
  { id: 'INV159', toolId: 'TR-159', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 50 mm', qty: 1 },
  { id: 'INV160', toolId: 'TR-160', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 50 mm x 12pt', qty: 3 },
  { id: 'INV161', toolId: 'TR-161', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 50 mm x 12pt', qty: 3 },
  { id: 'INV162', toolId: 'TR-162', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 48 mm', qty: 1 },
  { id: 'INV163', toolId: 'TR-163', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 48 mm', qty: 3 },
  { id: 'INV164', toolId: 'TR-164', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 46 mm', qty: 2 },
  { id: 'INV165', toolId: 'TR-165', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 46 mm x 12pt', qty: 3 },
  { id: 'INV166', toolId: 'TR-166', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 46 mm', qty: 1 },
  { id: 'INV167', toolId: 'TR-167', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 46 mm x 12pt', qty: 3 },
  { id: 'INV168', toolId: 'TR-168', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 43 mm', qty: 2 },
  { id: 'INV169', toolId: 'TR-169', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 41 mm', qty: 16 },
  { id: 'INV170', toolId: 'TR-170', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 41 mm', qty: 1 },
  { id: 'INV171', toolId: 'TR-171', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 38 mm', qty: 11 },
  { id: 'INV172', toolId: 'TR-172', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 38 mm', qty: 2 },
  { id: 'INV173', toolId: 'TR-173', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 38 mm X 12pt', qty: 2 },
  { id: 'INV174', toolId: 'TR-174', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 33 mm', qty: 2 },
  { id: 'INV175', toolId: 'TR-175', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 32 mm', qty: 1 },
  { id: 'INV176', toolId: 'TR-176', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 32 mm', qty: 6 },
  { id: 'INV177', toolId: 'TR-177', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 32 mm x 12pt', qty: 1 },
  { id: 'INV178', toolId: 'TR-178', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 30 mm', qty: 3 },
  { id: 'INV179', toolId: 'TR-179', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 30 mm', qty: 6 },
  { id: 'INV180', toolId: 'TR-180', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 30 mm x 12pt', qty: 1 },
  { id: 'INV181', toolId: 'TR-181', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 29 mm', qty: 3 },
  { id: 'INV182', toolId: 'TR-182', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4 " x 29 mm', qty: 1 },
  { id: 'INV183', toolId: 'TR-183', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 28 mm', qty: 2 },
  { id: 'INV184', toolId: 'TR-184', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 27 mm', qty: 5 },
  { id: 'INV185', toolId: 'TR-185', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1"X26mm', qty: 1 },
  { id: 'INV186', toolId: 'TR-186', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 27 mm', qty: 1 },
  { id: 'INV187', toolId: 'TR-187', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 26 mm', qty: 1 },
  { id: 'INV188', toolId: 'TR-188', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 25 mm', qty: 1 },
  { id: 'INV189', toolId: 'TR-189', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 24 mm', qty: 1 },
  { id: 'INV190', toolId: 'TR-190', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 24 mm', qty: 2 },
  { id: 'INV191', toolId: 'TR-191', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 22 mm', qty: 1 },
  { id: 'INV192', toolId: 'TR-192', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 22 mm', qty: 1 },
  { id: 'INV193', toolId: 'TR-193', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '3/4" x 21 mm', qty: 3 },
  { id: 'INV194', toolId: 'TR-194', category: 'Common Tool', merk: '', toolDesc: 'Socket Wrench', typeSize: '1" x 21 mm', qty: 1 },
  { id: 'INV195', toolId: 'TR-195', category: 'Common Tool', merk: '', toolDesc: 'Cutting Filter Tool', typeSize: 'Unknown', qty: 1 },
  { id: 'INV196', toolId: 'TR-196', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Chain Block', typeSize: '', qty: 2 },
  { id: 'INV197', toolId: 'TR-197', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Lever Block', typeSize: '', qty: 1 },
  { id: 'INV198', toolId: 'TR-198', category: 'Common Tool', merk: 'Tekiro', toolDesc: 'Starkey Shocket Male', typeSize: '', qty: 1 },
  { id: 'INV199', toolId: 'TR-199', category: 'Common Tool', merk: 'Tekiro', toolDesc: 'Starkey Shocket Famale', typeSize: '', qty: 1 },
  { id: 'INV200', toolId: 'TR-200', category: 'Common Tool', merk: 'Tekiro', toolDesc: 'El-key Shocket', typeSize: '', qty: 1 },
  { id: 'INV201', toolId: 'TR-201', category: 'Common Tool', merk: 'GEA', toolDesc: 'Chest Freezer', typeSize: '', qty: 1 },
  { id: 'INV202', toolId: 'TR-202', category: 'Common Tool', merk: 'ENERPAC', toolDesc: 'Hydraulic Cylinder 100 Ton', typeSize: '', qty: 1 },
  { id: 'INV203', toolId: 'TR-203', category: 'Common Tool', merk: 'ENERPAC', toolDesc: 'Hydraulic Cylinder 60 Ton', typeSize: '', qty: 2 },
  { id: 'INV204', toolId: 'TR-204', category: 'Common Tool', merk: 'ENERPAC', toolDesc: 'Hydraulic Cylinder 30 Ton', typeSize: '', qty: 1 },
  { id: 'INV205', toolId: 'TR-205', category: 'Common Tool', merk: 'ENERPAC', toolDesc: 'Hydraulic Cylinder 20 Ton', typeSize: '', qty: 1 },
  { id: 'INV206', toolId: 'TR-206', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'High Pressure Cleaner', typeSize: '', qty: 1 },
  { id: 'INV207', toolId: 'TR-207', category: 'Common Tool', merk: '', toolDesc: 'High Pressure Cleaner', typeSize: 'CDHPW400', qty: 1 },
  { id: 'INV208', toolId: 'TR-208', category: 'Common Tool', merk: '', toolDesc: 'Tool Crank Flywheel', typeSize: '99309', qty: 1 },
  { id: 'INV209', toolId: 'TR-209', category: 'Common Tool', merk: '', toolDesc: 'Tool Drag Link', typeSize: 'Unknown', qty: 1 },
  { id: 'INV210', toolId: 'TR-210', category: 'Common Tool', merk: '', toolDesc: 'Tool Flange Outer', typeSize: 'Unknown', qty: 1 },
  { id: 'INV211', toolId: 'TR-211', category: 'Common Tool', merk: '', toolDesc: 'Tool Flange Rear', typeSize: 'Unknown', qty: 1 },
  { id: 'INV212', toolId: 'TR-212', category: 'Common Tool', merk: 'SCANIA', toolDesc: 'Tool Hub Front', typeSize: '', qty: 2 },
  { id: 'INV213', toolId: 'TR-213', category: 'Common Tool', merk: 'SCANIA', toolDesc: 'Tool Hub Rear', typeSize: '', qty: 2 },
  { id: 'INV214', toolId: 'TR-214', category: 'Common Tool', merk: 'Nachi', toolDesc: 'Drill Bit Set', typeSize: '', qty: 1 },
  { id: 'INV215', toolId: 'TR-215', category: 'Common Tool', merk: 'PROGO TEHNIK', toolDesc: 'Fuel Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV216', toolId: 'TR-216', category: 'Common Tool', merk: '', toolDesc: 'Fuel Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV217', toolId: 'TR-217', category: 'Common Tool', merk: 'PROGO TEHNIK', toolDesc: 'Fuel Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV218', toolId: 'TR-218', category: 'Common Tool', merk: 'PROGO TEHNIK', toolDesc: 'Fuel Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV219', toolId: 'TR-219', category: 'Common Tool', merk: 'HYDAC', toolDesc: 'Fuel Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV220', toolId: 'TR-220', category: 'Common Tool', merk: 'PROGO TEHNIK', toolDesc: 'Oil Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV221', toolId: 'TR-221', category: 'Common Tool', merk: 'HYDAC', toolDesc: 'Oil Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV222', toolId: 'TR-222', category: 'Common Tool', merk: 'HYDAC', toolDesc: 'Oil Flushing Tool', typeSize: '', qty: 1 },
  { id: 'INV223', toolId: 'TR-223', category: 'Common Tool', merk: 'Tekiro', toolDesc: 'Mechanic Creeper', typeSize: '', qty: 1 },
  { id: 'INV224', toolId: 'TR-224', category: 'Common Tool', merk: 'Tekiro', toolDesc: 'Mechanic Creeper', typeSize: '', qty: 1 },
  { id: 'INV225', toolId: 'TR-225', category: 'Common Tool', merk: 'Makita', toolDesc: 'Hand Grinder', typeSize: '9553B', qty: 1 },
  { id: 'INV226', toolId: 'TR-226', category: 'Common Tool', merk: 'Makita', toolDesc: 'Cut Off Saw', typeSize: 'M2401B', qty: 1 },
  { id: 'INV227', toolId: 'TR-227', category: 'Common Tool', merk: 'Makita', toolDesc: 'Bech Grinder', typeSize: 'GB602', qty: 1 },
  { id: 'INV228', toolId: 'TR-228', category: 'Common Tool', merk: 'Krisbow', toolDesc: 'Fan Ventilator', typeSize: 'KW1000818', qty: 1 },
  { id: 'INV229', toolId: 'TR-229', category: 'Common Tool', merk: '', toolDesc: 'Hydraulic Trolley Jack', typeSize: 'Unknown', qty: 1 },
  { id: 'INV230', toolId: 'TR-230', category: 'Common Tool', merk: '', toolDesc: 'Hydraulic Trolley Jack', typeSize: 'Unknown', qty: 1 },
  { id: 'INV231', toolId: 'TR-231', category: 'Common Tool', merk: 'Artco', toolDesc: 'Wheelbarrow', typeSize: '', qty: 1 },
  { id: 'INV232', toolId: 'TR-232', category: 'Common Tool', merk: 'Artco', toolDesc: 'Wheelbarrow', typeSize: '', qty: 1 },
  { id: 'INV233', toolId: 'TR-233', category: 'Common Tool', merk: 'Artco', toolDesc: 'Wheelbarrow', typeSize: '', qty: 1 },
];

export const INITIAL_TOOLBOX_DETAILS = [
  { id: 'TD001', merk: 'Tekiro', toolDesc: 'Adjustable Wrech', typeSize: '6"', qty: 1 },
  { id: 'TD002', merk: 'Tekiro', toolDesc: 'Adjustable Wrech', typeSize: '12"', qty: 1 },
  { id: 'TD003', merk: 'Tekiro', toolDesc: 'Diagonal Cutting', typeSize: '6"', qty: 1 },
  { id: 'TD004', merk: 'Tekiro', toolDesc: 'Groove Joint Plier', typeSize: '10"', qty: 1 },
  { id: 'TD005', merk: 'Tekiro', toolDesc: 'Combination Plier', typeSize: '10"', qty: 1 },
  { id: 'TD006', merk: 'Tekiro', toolDesc: 'Snap Ring In', typeSize: '8mm', qty: 1 },
  { id: 'TD007', merk: 'Tekiro', toolDesc: 'Snap Ring Out', typeSize: '8mm', qty: 1 },
  { id: 'TD008', merk: 'Tekiro', toolDesc: 'Snap Ring In', typeSize: '12mm', qty: 1 },
  { id: 'TD009', merk: 'Tekiro', toolDesc: 'Snap Ring Out', typeSize: '12mm', qty: 1 },
  { id: 'TD010', merk: 'Tekiro', toolDesc: 'Chisel Punch Set', typeSize: '', qty: 1 },
  { id: 'TD011', merk: 'Tekiro', toolDesc: 'Pahat / Betel', typeSize: '', qty: 1 },
  { id: 'TD012', merk: 'Tekiro', toolDesc: 'Locking Plier/Pas Grip', typeSize: '', qty: 1 },
  { id: 'TD013', merk: 'Tekiro', toolDesc: 'Hammer Tembaga', typeSize: '1kg', qty: 1 },
  { id: 'TD014', merk: 'Tekiro', toolDesc: 'Hammer Pena', typeSize: '', qty: 1 },
  { id: 'TD015', merk: 'Tekiro', toolDesc: 'Kikir Set', typeSize: '', qty: 1 },
  { id: 'TD016', merk: 'Tekiro', toolDesc: 'Gergaji Besi', typeSize: '', qty: 1 },
  { id: 'TD017', merk: 'Tekiro', toolDesc: 'Universal Joint', typeSize: '1/2"DR', qty: 1 },
  { id: 'TD018', merk: 'Tekiro', toolDesc: 'Extension Bar', typeSize: '1/2"DR3"', qty: 1 },
  { id: 'TD019', merk: 'Tekiro', toolDesc: 'Extension Bar', typeSize: '1/2"DR5"', qty: 1 },
  { id: 'TD020', merk: 'Tekiro', toolDesc: 'Extension Bar', typeSize: '1/2"DR10"', qty: 1 },
  { id: 'TD021', merk: 'Tekiro', toolDesc: 'Extension Bar', typeSize: '3/4"DR8"', qty: 1 },
  { id: 'TD022', merk: 'Tekiro', toolDesc: 'Extension Bar', typeSize: '3/4"DR16"', qty: 1 },
  { id: 'TD023', merk: 'Tekiro', toolDesc: 'Water Pump', typeSize: 'Plier', qty: 1 },
  { id: 'TD024', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR10mm', qty: 1 },
  { id: 'TD025', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR11mm', qty: 1 },
  { id: 'TD026', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR12mm', qty: 1 },
  { id: 'TD027', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR13mm', qty: 1 },
  { id: 'TD028', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR14mm', qty: 1 },
  { id: 'TD029', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR15mm', qty: 1 },
  { id: 'TD030', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR16mm', qty: 1 },
  { id: 'TD031', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR17mm', qty: 1 },
  { id: 'TD032', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR18mm', qty: 1 },
  { id: 'TD033', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR19mm', qty: 1 },
  { id: 'TD034', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR20mm', qty: 1 },
  { id: 'TD035', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR21mm', qty: 1 },
  { id: 'TD036', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR22mm', qty: 1 },
  { id: 'TD037', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR23mm', qty: 1 },
  { id: 'TD038', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR24mm', qty: 1 },
  { id: 'TD039', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR25mm', qty: 1 },
  { id: 'TD040', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR27mm', qty: 1 },
  { id: 'TD041', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR28mm', qty: 1 },
  { id: 'TD042', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR30mm', qty: 1 },
  { id: 'TD043', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR32mm', qty: 1 },
  { id: 'TD044', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR17mm', qty: 1 },
  { id: 'TD045', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR19mm', qty: 1 },
  { id: 'TD046', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR21mm', qty: 1 },
  { id: 'TD047', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR22mm', qty: 1 },
  { id: 'TD048', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR23mm', qty: 1 },
  { id: 'TD049', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR24mm', qty: 1 },
  { id: 'TD050', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR27mm', qty: 1 },
  { id: 'TD051', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR29mm', qty: 1 },
  { id: 'TD052', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR30mm', qty: 1 },
  { id: 'TD053', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR32mm', qty: 1 },
  { id: 'TD054', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '6PT3/4"DR36mm', qty: 1 },
  { id: 'TD055', merk: 'Tekiro', toolDesc: 'Slidding T', typeSize: 'Bar1/2"DR12"', qty: 1 },
  { id: 'TD056', merk: 'Tekiro', toolDesc: 'Slidding T', typeSize: 'Bar3/4"DR12"', qty: 1 },
  { id: 'TD057', merk: 'Tekiro', toolDesc: 'Rachet', typeSize: '1/2" DR', qty: 1 },
  { id: 'TD058', merk: 'Tekiro', toolDesc: 'Rachet', typeSize: '3/4" DR', qty: 1 },
  { id: 'TD059', merk: 'Tekiro', toolDesc: 'Magnetic Tools', typeSize: '', qty: 1 },
  { id: 'TD060', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '6-7mm', qty: 1 },
  { id: 'TD061', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '8-9mm', qty: 1 },
  { id: 'TD062', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '10-11mm', qty: 1 },
  { id: 'TD063', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '12-13mm', qty: 1 },
  { id: 'TD064', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '14-15mm', qty: 1 },
  { id: 'TD065', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '16-17mm', qty: 1 },
  { id: 'TD066', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '18-19mm', qty: 1 },
  { id: 'TD067', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '20-22mm', qty: 1 },
  { id: 'TD068', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '21-23mm', qty: 1 },
  { id: 'TD069', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '24-27mm', qty: 1 },
  { id: 'TD070', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '25-28mm', qty: 1 },
  { id: 'TD071', merk: 'Tekiro', toolDesc: 'Open End Wrench', typeSize: '30-32mm', qty: 1 },
  { id: 'TD072', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '6mm', qty: 1 },
  { id: 'TD073', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '7mm', qty: 1 },
  { id: 'TD074', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '8mm', qty: 1 },
  { id: 'TD075', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '9mm', qty: 1 },
  { id: 'TD076', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '10mm', qty: 1 },
  { id: 'TD077', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '12mm', qty: 1 },
  { id: 'TD078', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '13mm', qty: 1 },
  { id: 'TD079', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '14mm', qty: 1 },
  { id: 'TD080', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '16mm', qty: 1 },
  { id: 'TD081', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '17mm', qty: 1 },
  { id: 'TD082', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '19mm', qty: 1 },
  { id: 'TD083', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '22mm', qty: 1 },
  { id: 'TD084', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '24mm', qty: 1 },
  { id: 'TD085', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '27mm', qty: 1 },
  { id: 'TD086', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '30mm', qty: 1 },
  { id: 'TD087', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '32mm', qty: 1 },
  { id: 'TD088', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '6-7mm', qty: 1 },
  { id: 'TD089', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '8-9mm', qty: 1 },
  { id: 'TD090', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '10-11mm', qty: 1 },
  { id: 'TD091', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '12-13mm', qty: 1 },
  { id: 'TD092', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '14-15mm', qty: 1 },
  { id: 'TD093', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '16-17mm', qty: 1 },
  { id: 'TD094', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '18-19mm', qty: 1 },
  { id: 'TD095', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '20-22mm', qty: 1 },
  { id: 'TD096', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '21-23mm', qty: 1 },
  { id: 'TD097', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '24-27mm', qty: 1 },
  { id: 'TD098', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '25-28mm', qty: 1 },
  { id: 'TD099', merk: 'Tekiro', toolDesc: 'Double Ring Wrench', typeSize: '30-32mm', qty: 1 },
  { id: 'TD100', merk: 'Tekiro', toolDesc: 'Elenkey', typeSize: '12mm', qty: 1 },
  { id: 'TD101', merk: 'Tekiro', toolDesc: 'Elenkey', typeSize: '14mm', qty: 1 },
  { id: 'TD102', merk: 'Tekiro', toolDesc: 'Elenkey', typeSize: '17mm', qty: 1 },
  { id: 'TD103', merk: 'Tekiro', toolDesc: 'Elenkey', typeSize: '19mm', qty: 1 },
  { id: 'TD104', merk: 'Tekiro', toolDesc: 'Elenkey', typeSize: '22mm', qty: 1 },
  { id: 'TD105', merk: 'Tekiro', toolDesc: 'Elenkey Set', typeSize: '', qty: 1 },
  { id: 'TD106', merk: 'Tekiro', toolDesc: 'Extra long', typeSize: '', qty: 1 },
  { id: 'TD107', merk: 'Tekiro', toolDesc: 'Filler Gauge', typeSize: '', qty: 1 },
  { id: 'TD108', merk: 'Tekiro', toolDesc: 'Screw Driver', typeSize: '', qty: 1 },
  { id: 'TD109', merk: 'Tekiro', toolDesc: 'Catridge Oil Filtef', typeSize: '', qty: 1 },
  { id: 'TD110', merk: 'Tekiro', toolDesc: 'Half Moon', typeSize: 'Wrench10-12mm', qty: 1 },
  { id: 'TD111', merk: 'Tekiro', toolDesc: 'Half Moon', typeSize: 'Wrench14-17mm', qty: 1 },
  { id: 'TD112', merk: 'Tekiro', toolDesc: 'Half Moon', typeSize: 'Wrench19-22mm', qty: 1 },
  { id: 'TD113', merk: 'Tekiro', toolDesc: 'Adaptor Socket', typeSize: '1/2"-3/4"', qty: 1 },
  { id: 'TD114', merk: 'Tekiro', toolDesc: 'Adaptor Socket', typeSize: '3/4"-1/2"', qty: 1 },
  { id: 'TD115', merk: 'Tekiro', toolDesc: 'Terminal Crimping', typeSize: '', qty: 1 },
  { id: 'TD116', merk: 'Tekiro', toolDesc: 'Tomy Bar', typeSize: '', qty: 1 },
  { id: 'TD117', merk: 'Tekiro', toolDesc: 'Socket Wrench', typeSize: '12PT1/2"DR42mm', qty: 1 },
  { id: 'TD118', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)11mm', qty: 1 },
  { id: 'TD119', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)15mm', qty: 1 },
  { id: 'TD120', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)18mm', qty: 1 },
  { id: 'TD121', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)20mm', qty: 1 },
  { id: 'TD122', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)21mm', qty: 1 },
  { id: 'TD123', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)23mm', qty: 1 },
  { id: 'TD124', merk: 'Tekiro', toolDesc: 'Combination Wrench', typeSize: '(Pas-Ring)25mm', qty: 1 },
  { id: 'TD125', merk: 'Tekiro', toolDesc: 'Test Pen', typeSize: '', qty: 1 },
];

export const INITIAL_TOOLBOXES: Toolbox[] = [
  { id: 'TB01', idToolbox: 'TB01', name: 'FAJAR RAMADHAN', nrp: '30170132', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB02', idToolbox: 'TB02', name: 'MUHAMMAD RIZKI', nrp: '30170134', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB03', idToolbox: 'TB03', name: 'HARIYADI', nrp: '30180005', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB04', idToolbox: 'TB04', name: 'DIKY HARIADI', nrp: '30180482', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB05', idToolbox: 'TB05', name: 'AGUNG PRATAMA', nrp: '30180544', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB06', idToolbox: 'TB06', name: 'FAJAR SUSANTO', nrp: '30180547', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB07', idToolbox: 'TB07', name: 'MUHAMMAD ANANDA HERMANTO', nrp: '30180657', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB08', idToolbox: 'TB08', name: 'AHMAD ZULFADIN', nrp: '30200513', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB09', idToolbox: 'TB09', name: 'ANDRE YUDA SETIAWAN', nrp: '30200515', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB10', idToolbox: 'TB10', name: 'OKI SANDI SAPUTRA & MUHAMMAD ARBA ISA', nrp: '30180654', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB11', idToolbox: 'TB11', name: 'ROMY FIRMANSYAH', nrp: '30210460', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB12', idToolbox: 'TB12', name: 'MUHAMMAD AYUB', nrp: '30210466', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB13', idToolbox: 'TB13', name: 'ANTONG YOFI PAHLEFI PUTERA', nrp: '30220869', section: 'WHEEL BIG', toolCount: 125 },
  { id: 'TB14', idToolbox: 'TB14', name: 'JUNAIDI A', nrp: '30160014', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB15', idToolbox: 'TB15', name: "MUHAMMAD SAFE'I HELMI", nrp: '30230237', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB16', idToolbox: 'TB16', name: 'KURNIAWAN EFENDI', nrp: '30160089', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB17', idToolbox: 'TB17', name: 'RIZKY SAPUTRA', nrp: '30170096', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB18', idToolbox: 'TB18', name: 'MUHAMMAD NOOR IRPANSYAH', nrp: '30170133', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB19', idToolbox: 'TB19', name: 'JUNAIDI B', nrp: '30170135', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB20', idToolbox: 'TB20', name: 'ANDIKA SAPUTRA', nrp: '30170406', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB21', idToolbox: 'TB21', name: 'JOKO SUPRIANTO', nrp: '30180476', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB22', idToolbox: 'TB22', name: 'SYAHRUL', nrp: '30180542', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB23', idToolbox: 'TB23', name: 'WILDANI AMRULLAH', nrp: '30180656', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB24', idToolbox: 'TB24', name: 'KHOIRUL EFENDI', nrp: '30190005', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB25', idToolbox: 'TB25', name: 'AIDI NURAHMAN', nrp: '30190008', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB26', idToolbox: 'TB26', name: 'RADEN MUHAMMAD ALDO', nrp: '30200440', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB27', idToolbox: 'TB27', name: 'JAWAR NAHAMPUN', nrp: '30200507', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB28', idToolbox: 'TB28', name: 'TRI SUKO ATMOJO', nrp: '30210467', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB29', idToolbox: 'TB29', name: 'RETNO ARISHANDI', nrp: '30210576', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB30', idToolbox: 'TB30', name: "IMAM SYAFI'I", nrp: '30210875', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB31', idToolbox: 'TB31', name: 'HENDRIK DIAN PRASETYO', nrp: '30220459', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB32', idToolbox: 'TB32', name: 'MUHAMMAD HIFZI', nrp: '30220622', section: 'WHEEL SMALL', toolCount: 125 },
  { id: 'TB34', idToolbox: 'TB34', name: 'HAFAIRI ZIKRI', nrp: '30160010', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB35', idToolbox: 'TB35', name: 'MUHAMMAD AMRULLAH', nrp: '30170301', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB36', idToolbox: 'TB36', name: 'MUHAMMAD TAUPIK', nrp: '30170319', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB37', idToolbox: 'TB37', name: 'AGUNG SUHARTANTO', nrp: '30180041', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB38', idToolbox: 'TB38', name: 'ANGGA DWI SAPUTRA', nrp: '30180437', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB39', idToolbox: 'TB39', name: 'MUHAMMAD TAMBRIN', nrp: '30180572', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB40', idToolbox: 'TB40', name: 'EDY KURNIAWAN', nrp: '30180574', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB41', idToolbox: 'TB41', name: 'EDY PURNOMO', nrp: '30190006', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB42', idToolbox: 'TB42', name: 'EKO HERRY ANGGIANTO', nrp: '30210331', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB43', idToolbox: 'TB43', name: 'EKO WINARKO', nrp: '30210425', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB44', idToolbox: 'TB44', name: 'M. RIZAL ARAFATANNOOR', nrp: '30220810', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB45', idToolbox: 'TB45', name: 'MUHAMMAD FAJAR HABIBI', nrp: '30221217', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB46', idToolbox: 'TB46', name: 'ARIS SAKATI', nrp: '30230008', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB47', idToolbox: 'TB47', name: 'HILMAN MARTHA DINATA', nrp: '30230246', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB48', idToolbox: 'TB48', name: 'RIDHANI RAHMAN', nrp: '30220560', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB49', idToolbox: 'TB49', name: 'AHMAD MUKHLISIN', nrp: '30220541', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB50', idToolbox: 'TB50', name: 'IFANSYAH PRAMUDIA', nrp: '30210669', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB51', idToolbox: 'TB51', name: 'ANDREAN SAPUTRA', nrp: '30230563', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB52', idToolbox: 'TB52', name: 'MUHAMMAD ALIF AKBAR', nrp: '30210666', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB53', idToolbox: 'TB53', name: 'MUHAMMAD RIDHANI', nrp: '30210876', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB54', idToolbox: 'TB54', name: 'ZAINUDDIN', nrp: '30220490', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB55', idToolbox: 'TB55', name: 'MUHAMMAD ILMI', nrp: '30180470', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB56', idToolbox: 'TB56', name: 'DARUSMAN JULIANTO', nrp: '30180573', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB57', idToolbox: 'TB57', name: 'RUSMAN', nrp: '30190003', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB58', idToolbox: 'TB58', name: 'SUPRIYANTO', nrp: '30190012', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB59', idToolbox: 'TB59', name: 'SAPUTRA GILANG WICAKSONO', nrp: '30200510', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB60', idToolbox: 'TB60', name: 'MUHAMMAD ALDI & KHOIRUL ANWAR', nrp: '30210228', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB61', idToolbox: 'TB61', name: 'THORIQ AZIZ', nrp: '30210499', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB62', idToolbox: 'TB62', name: 'MUHAMMAD ABYL REZA PRAMUDYA', nrp: '30210877', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB63', idToolbox: 'TB63', name: 'RAHMAT JAZULI', nrp: '30220457', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB64', idToolbox: 'TB64', name: 'HERU SETYANTO', nrp: '30220910', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB65', idToolbox: 'TB65', name: 'RETNO TONY PRIBADI', nrp: '30170351', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB66', idToolbox: 'TB66', name: 'MUHAMMAD ERFANI', nrp: '30160094', section: 'SSE MECHANIC', toolCount: 125 },
  { id: 'TB67', idToolbox: 'TB67', name: 'RAHMAT DWI ALFITRA', nrp: '30240004', section: 'TRACK MECHANIC', toolCount: 125 },
  { id: 'TB68', idToolbox: 'TB68', name: 'MUHAMMAD IHSANUL AMIN', nrp: '30240193', section: 'TRACK MECHANIC', toolCount: 125 },
];
